# Generated by Django 6.0.4 on 2026-05-18 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCategoriaTriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad_ia', models.IntegerField(blank=True, null=True)),
                ('motivo_en_ese_momento', models.TextField()),
                ('origen', models.CharField(choices=[('ia', 'Inteligencia artificial'), ('medico', 'Médico'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_consultas', to='triaje.categoriatriage')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_categorias', to='triaje.consulta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_categoria_triaje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de categoría de triaje',
                'verbose_name_plural': 'Históricos de categorías de triaje',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
