# Generated by Django 6.0.4 on 2026-04-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='orden_manual',
            field=models.IntegerField(default=0),
        ),
    ]
